### ISSUE TITLE
Finish island glitch

### ISSUE THREAD

**Issue by flxrr** [McPlayHDnet/McPlayHD.net#60] opened 2021-07-11 19:01 UTC
you can jump to someone elses finish island in fastbuilder 

if u jump very carefully u can jump on the very edge of the stairs of the island on the left of u
![2021-07-11_20 37 52](https://user-images.githubusercontent.com/87279972/125207106-c39ad300-e28a-11eb-9257-9773098e14f1.png)
![2021-07-11_21 00 26](https://user-images.githubusercontent.com/87279972/125207170-14aac700-e28b-11eb-8e1a-1320e3a968ae.png)

**Comment by Worldbuilder777** [comment] 2021-08-01 15:04
not sure if that is even worth fixing since you cannot gain any advantage through that
but maybe someone else can come up with an argument as to why we should?

**Comment by flxrr** [comment] 2021-08-02 06:55
idk its a bug so i thought i should report it here incase it was a problem

**Comment by McPlayHD** [comment] 2021-08-03 12:30
@flxrr could you tell me the exact X position that you just barely can stand on without falling off the opponent's island? I also need the slot number you are in. So if you are in slot 2 and can jump on the island of slot 1 I need the information "Slot 2, X=?"

**Comment by flxrr** [comment] 2021-08-03 20:19
it works on every slot on the map, except for slot 1 because theres no island to the left of slot 1

ill check what the exact position is the next time i can get online which is tomorrow

**Comment by flxrr** [comment] 2021-08-05 12:06
![2021-08-05_14 01 39](https://user-images.githubusercontent.com/87279972/128347009-77b00b7f-b7ba-4606-9872-0550ab0346c3.png)
look at the F3 coords

**Comment by McPlayHD** [comment] 2021-08-05 13:33
I still need to know the slot you were in counting from the left side

**Comment by flxrr** [comment] 2021-08-05 13:40
I said, it works on every slot except for the first one because theres no slot on the left of slot 1

**Comment by McPlayHD** [comment] 2021-08-06 14:44
I still need to know the slot you were in when taking the coordinates. That's because I need the relative coordinates you are at. Basically, the X value is different for every slot so I really need that information. The easiest thing would be if you were on slot 2 and took the coordinates.

**Comment by flxrr** [comment] 2021-08-06 21:57
ohhhhhhh okayy ill do that tomorrow when i can log on

**Comment by flxrr** [comment] 2021-08-07 09:53
![2021-08-07_11 52 09](https://user-images.githubusercontent.com/87279972/128596329-641bdc21-3735-46f9-aebc-0025867f9b29.png)
slot 2

**Comment by McPlayHD** [comment] 2021-08-07 11:40
Great. Thanks a lot! I will now have a look at why this happens and if we are able to fix it easily or not.

**Comment by flxrr** [comment] 2021-08-07 19:12
goodluck

**Comment by McPlayHD** [comment] 2024-10-24 22:27
I was able to reproduce the issue. Seems like the left bound of each island might be one block too wide.

**Comment by McPlayHD** [comment] 2024-10-24 22:30
I was able to reproduce the issue. ~~Seems like the left bound of each island might be one block too wide.~~
Actually the finish island is one block wider than the start island and since the player's hitbox can clip 0.3 blocks into the void, it doesn't register for teleporting back. I suggest we just make the bounds 0.3 blocks more narrow on both sides.

**Comment by McPlayHD** [comment] 2024-10-25 08:20
Should be fixed after next FastBuilder server restarts.

**Closed by McPlayHD** 2024-10-25 08:20 UTC
Labels: bug, low priority
