### ISSUE TITLE
Bug with Anticheat npc (i think)

### ISSUE THREAD

**Issue by obvTiger** [McPlayHDnet/McPlayHD.net#71] opened 2021-08-30 05:35 UTC
Just jumping around in the lobby when suddenly a NPC appear
https://user-images.githubusercontent.com/83970850/131289996-88f40f8b-7a30-4f16-bb05-15058919bb44.mp4

I don't know how to reproduce the bug, but other people could not see it 

and yes N8W0 is cheating in the background

**Comment by McPlayHD** [comment] 2021-09-06 15:48
This seems to be an NPC from the AntiCheat. Since there is no clear way in how to reproduce this issue I will put the "wontfix" label on it and close it. If you can find out how to reproduce in the future just write again.

**Closed by McPlayHD** 2021-09-06 15:48 UTC
Labels: bug, wontfix, low priority
