### ISSUE TITLE
Overwatch error "invalid replay"

### ISSUE THREAD

**Issue by TrooperCH** [McPlayHDnet/McPlayHD.net#14] opened 2020-09-01 14:06 UTC
It seems to occur very frequently that replays in overwatch tell you "invalid replay" after you have watched them.

**Comment by McPlayHD** [comment] 2020-09-01 14:28
- Who did it happen to?
- What was the exact time it happened?
- Did it load the same replay again all the time?`
- Did other errors occur?
- Was someone just confirming / banning replays? (Because then it it usual that this happens... If a replay gets confirmed for example and then a player votes for the replay there has to be the *invalid replay* error)

**Comment by TrooperCH** [comment] 2020-09-01 14:44
- 2 random players from discord and KBDino
- 2x no idea, kbdino around 31.08.2020:18:50 (http://prntscr.com/u9ok3x)
- Pretty sure that was not the case
- I don't think players and helpers can get any error in OW and if they can, no occurance of other errors was reported
- No idea

**Comment by McPlayHD** [comment] 2020-09-01 15:41
Because the latest patch with a specific bugfix for this issue was after the given date I will now close this issue. Reopen if it happens again please (with all the told information)
![image](https://user-images.githubusercontent.com/7106489/91874311-5ab1fa00-ec7a-11ea-8738-1d0b3ae96d70.png)

**Closed** 2020-09-01 15:41 UTC
Labels: bug, question
