### ISSUE TITLE
Overwatch holograms bugged movement

### ISSUE THREAD

**Issue by stupxd** [McPlayHDnet/McPlayHD.net#63] opened 2021-07-26 20:41 UTC
There's 2 issues with holograms movement:
1. Micro jitter (it goes left and right even tho player just walks straight) when u watch tick by tick or just normally
2. Huge shift to the left when u pause and go back by 0.5 sec.

Both things can be seen in this video:

https://user-images.githubusercontent.com/83234016/127056041-687be6ed-1c24-4275-86ca-960c95d1baee.mp4

**Comment by McPlayHD** [comment] 2021-07-27 12:01
I honestly don't think we can fix this. It looks like this is a problem of Minecraft itself where too small position updates result in no update at all.
Also, this is not really of a high priority since it doesn't really affect the decision making.
Furthermore, we don't see this happening all the time so unless you can give us an exact "how to reproduce" tutorial in it working fine before and not working smoothly anymore after we can't really fix anything at all.
I'll close this issue but if you find out the reason for this jittering you can always reopen this issue or create a new one.

**Closed by McPlayHD** 2021-07-27 12:01 UTC
Labels: low priority, wontfix
