### ISSUE TITLE
ignore and chatlog issues on /nick

### ISSUE THREAD

**Issue by TrooperCH** [McPlayHDnet/McPlayHD.net#89] opened 2021-10-05 14:16 UTC
Neither /ignore <name> nor /chatlog <name> is possible on nicked players

**Comment by McPlayHD** [comment] 2021-10-05 16:22
Duplicate of https://github.com/McPlayHDnet/McPlayHD.net/issues/50

**Closed by McPlayHD** 2021-10-05 16:22 UTC
Labels: bug, URGENT
